# Form implementation generated from reading ui file 'dangnhap.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1163, 600)
        MainWindow.setStyleSheet("background-color: rgb(255, 207, 208);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_taikhoan = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_taikhoan.setGeometry(QtCore.QRect(380, 130, 511, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.txt_taikhoan.setFont(font)
        self.txt_taikhoan.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;      \n"
"border: 1px solid #c0392b; \n"
"\n"
"")
        self.txt_taikhoan.setObjectName("txt_taikhoan")
        self.lbl_taikhoan = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_taikhoan.setGeometry(QtCore.QRect(210, 130, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_taikhoan.setFont(font)
        self.lbl_taikhoan.setObjectName("lbl_taikhoan")
        self.lbl_matkhau = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_matkhau.setGeometry(QtCore.QRect(210, 220, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_matkhau.setFont(font)
        self.lbl_matkhau.setObjectName("lbl_matkhau")
        self.ptb_dangnhap = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ptb_dangnhap.setGeometry(QtCore.QRect(390, 360, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.ptb_dangnhap.setFont(font)
        self.ptb_dangnhap.setStyleSheet("QPushButton {\n"
"   \n"
"    background-color: rgb(177, 0, 0);\n"
"    color: white;             \n"
"    border-radius: 15px;      \n"
"    border: 1px solid #c0392b; \n"
"    padding: 5px 15px;         \n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff5e4d;\n"
"}")
        self.ptb_dangnhap.setObjectName("ptb_dangnhap")
        self.ptb_dangky = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ptb_dangky.setGeometry(QtCore.QRect(640, 360, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.ptb_dangky.setFont(font)
        self.ptb_dangky.setStyleSheet("QPushButton {\n"
"   \n"
"    background-color: rgb(177, 0, 0);\n"
"    color: white;             \n"
"    border-radius: 15px;      \n"
"    border: 1px solid #c0392b; \n"
"    padding: 5px 15px;         \n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff5e4d;\n"
"}")
        self.ptb_dangky.setObjectName("ptb_dangky")
        self.txt_matkhau = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_matkhau.setGeometry(QtCore.QRect(380, 220, 511, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.txt_matkhau.setFont(font)
        self.txt_matkhau.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;      \n"
"border: 1px solid #c0392b; \n"
"\n"
"")
        self.txt_matkhau.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_matkhau.setObjectName("txt_matkhau")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1163, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_taikhoan.setText(_translate("MainWindow", "Tài khoản:"))
        self.lbl_matkhau.setText(_translate("MainWindow", "Mật khẩu:"))
        self.ptb_dangnhap.setText(_translate("MainWindow", "Đăng nhập"))
        self.ptb_dangky.setText(_translate("MainWindow", "Đăng ký"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
